### Load packages

In [1]:
import torch

In [3]:
torch.cuda.is_available()

True

### Tensors

In [2]:
random_tensor = torch.rand(size=(3,4))

In [4]:
random_tensor, random_tensor.shape, random_tensor.ndim

(tensor([[0.3693, 0.0030, 0.9571, 0.2151],
         [0.9877, 0.8751, 0.5762, 0.2563],
         [0.6159, 0.2634, 0.6346, 0.6085]]),
 torch.Size([3, 4]),
 2)

In [7]:
zeros= torch.zeros(size=(3,4,1))
ones= torch.ones(size=(3,4,1))
zeros, ones, zeros.dtype, ones.dtype

(tensor([[[0.],
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          [0.]],
 
         [[0.],
          [0.],
          [0.],
          [0.]]]),
 tensor([[[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]]]),
 torch.float32,
 torch.float32)

In [9]:
tensor_range = torch.arange(start=1, end= 10, step =1)
tensor_dupe = torch.zeros_like(tensor_range)
tensor_range, tensor_dupe

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))