### Load packages

In [35]:
import torch
import numpy as np
import random as rn

In [3]:
torch.cuda.is_available()

True

### Tensors

In [2]:
random_tensor = torch.rand(size=(3,4))

In [4]:
random_tensor, random_tensor.shape, random_tensor.ndim

(tensor([[0.3693, 0.0030, 0.9571, 0.2151],
         [0.9877, 0.8751, 0.5762, 0.2563],
         [0.6159, 0.2634, 0.6346, 0.6085]]),
 torch.Size([3, 4]),
 2)

In [ ]:
zeros= torch.zeros(size=(3,4,1))
ones= torch.ones(size=(3,4,1))
zeros, ones, zeros.dtype, ones.dtype

In [9]:
tensor_range = torch.arange(start=1, end= 10, step =1)
tensor_dupe = torch.zeros_like(tensor_range)
tensor_range, tensor_dupe

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [10]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

### Matrix Multiplication

In [11]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [14]:
mat_mul_a_b = torch.matmul(tensor_A, tensor_B.T)
mat_mul_a_b

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Tensor Operations 

In [18]:
x = torch.arange(10, 100, 10)
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32))

print(f"The minimum is at:{torch.argmin(x)} and the maximum is at {torch.argmax(x)}")

The minimum is at:0 and the maximum is at 8


### Reshaing and squeezing

In [19]:
x= torch. arange(1,8)
x_reshape = x.reshape(shape=(1,7))
x_reshape.shape

torch.Size([1, 7])

In [20]:
z= x.view(1,7)
z.shape

torch.Size([1, 7])

In [22]:
# Changing x changes z
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [26]:
x_stacked = torch.stack([x,x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5, 5],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7]])

In [28]:
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshape.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7])
New shape: torch.Size([7])


In [29]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7])
Previous shape: torch.Size([7])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7]])
New shape: torch.Size([1, 7])


### Indexing

In [30]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [31]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [34]:
array =np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor+1

(array([1, 2, 3, 4, 5, 6, 7]), tensor([2, 3, 4, 5, 6, 7, 8]))

### Removing randomness from Random

In [38]:
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Using the GPUs

In [39]:
!nvidia-smi

Sun Apr 26 20:46:31 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.126.09             Driver Version: 580.126.09     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti     Off |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              1W /   41W |       9MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [40]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [41]:
torch.cuda.device_count()

1

In [43]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [44]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [45]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [46]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])